name: CI

on: [push, pull_request]
jobs:
  test_musl:
    name: "Test with ${{ matrix.compiler.name }}/musl/libstdc++/BFD on Alpine Linux"
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: GCC
            packages: g++
            cc: gcc
            cxx: g++
          - name: Clang
            packages: g++ clang21
            cc: clang-21
            cxx: clang++-21
    steps:
      - name: Add testing repository
        run: echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories # only needed for wayfire-dev

      - name: Install dependencies
        run: |
          apk --no-cache add \
            git \
            ${{ matrix.compiler.packages }} \
            binutils \
            pkgconf \
            meson \
            ninja \
            musl-dev \
            gtkmm4-dev \
            vala \
            gobject-introspection-dev \
            ddcutil \
            pulseaudio-dev \
            pipewire-dev \
            wireplumber-dev \
            libdbusmenu-glib-dev \
            alsa-lib-dev \
            yyjson-dev \
            linux-pam-dev \
            util-linux-login \
            openssl-dev \
            wayland-protocols \
            wayfire-dev \
            gtk4-layer-shell-dev

      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: WayfireWM/wf-shell
          path: wf-shell

      - name: Build
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          cd wf-shell
          meson setup build --prefix=/usr
          ninja -v -C build
          ninja -v -C build install

  test_code_style:
    name: "Check code style with uncrustify"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake gcc make

      - name: Checkout uncrustify
        uses: actions/checkout@v7
        with:
          repository: ammen99/uncrustify
          path: uncrustify

      - name: Build uncrustify
        run: |
          cd uncrustify
          mkdir build
          cd build
          cmake ..
          make

      - name: Checkout wf-shell
        uses: actions/checkout@v7
        with:
          path: wf-shell

      - name: Run uncrustify check
        run: |
          cd wf-shell
          wget https://raw.githubusercontent.com/WayfireWM/wayfire/master/uncrustify.ini
          git ls-files | grep "hpp$\|cpp$" | xargs ../uncrustify/build/uncrustify -c uncrustify.ini --no-backup --replace
          git diff --exit-code
